### ISSUE TITLE
Object Selector

### ISSUE THREAD

**Issue by BraunreutherA** [vojtechportes/react-query-builder#23]
Hi, 

I'd like to build a segmentation featue with react-query-builder. Is it somehow possible to have a text input field on the left hand side? 
In my case we have query params parsed to an Object: `{[key: string]: string}` where the keys can be anything. With select fields this would not work. 

Could this already be done somehow or would it be a completely new feature?

Best 
Alex

**Comment by vojtechportes** [comment]
@BraunreutherA Hi Alex, this is currently not possible, unless you use parsed query string keys as initial field configuration. But I guess this is not something you are looking for.

Currently, I can think of two possible solution.
One is to make fields property optional. If fields wouldn't be set, you would be "only" able to type name of "field" manually and use operators that would be predefined as property on Builder component in this case instead of on fields object. Something like this. 

`
<Builder
    readOnly={false}
    operators={[EQUAL, NOT_EQUAL, SMALLER, LARGER]}
    data={data}
    components={components}
    onChange={data => console.log(data)}
  />
`

The other option is to allow adding new fields through fields select.

Let me know if this would work for you. First solution is definitely easier to implement and I guess I might be able to do it during this week. Second solution would be most probably bit more complex and I would still need to think about it in detail.
